{% set version = "2.1-22" %}
{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-r2winbugs
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/R2WinBUGS_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/R2WinBUGS/R2WinBUGS_{{ version }}.tar.gz
  sha256: aed74097c7c4552cf139828babf25555a67270925524bdd5856fa7cfd8d18179

build:
  merge_build_host: true  # [win]
  number: 0
  noarch: generic
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{ posix }}zip               # [win]
  host:
    - r-base
    - r-boot
    - r-coda >=0.11_0
  run:
    - r-base
    - r-boot
    - r-coda >=0.11_0

test:
  commands:
    - $R -e "library('R2WinBUGS')"           # [not win]
    - "\"%R%\" -e \"library('R2WinBUGS')\""  # [win]

about:
  home: https://CRAN.R-project.org/package=R2WinBUGS
  license: GPL-2.0-only
  summary: Invoke a 'BUGS' model in 'OpenBUGS' or 'WinBUGS', a class "bugs" for 'BUGS'  results and functions to work with that class. Function write.model() allows a 'BUGS' model file to be written.   The class and auxiliary functions could be used with other MCMC programs, including 'JAGS'.
  license_family: GPL2
  license_file:
    - {{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-2

extra:
  recipe-maintainers:
    - conda-forge/r

# Package: R2WinBUGS
# Title: Running 'WinBUGS' and 'OpenBUGS' from 'R' / 'S-PLUS'
# Date: 2015-07-29
# Version: 2.1-21
# Author: originally written by Andrew Gelman <gelman@stat.columbia.edu>; changes and packaged by Sibylle Sturtz <sturtz@statistik.tu-dortmund.de> and Uwe Ligges <ligges@statistik.tu-dortmund.de>. With considerable contributions by Gregor Gorjanc <gregor.gorjanc@bfro.uni-lj.si> and Jouni Kerman <kerman@stat.columbia.edu>. Ported to S-PLUS by Insightful Corp.
# Description: Invoke a 'BUGS' model in 'OpenBUGS' or 'WinBUGS', a class "bugs" for 'BUGS'  results and functions to work with that class. Function write.model() allows a 'BUGS' model file to be written.   The class and auxiliary functions could be used with other MCMC programs, including 'JAGS'.
# Depends: R (>= 2.13.0), coda (>= 0.11-0), boot
# Imports: utils, stats, graphics
# Suggests: BRugs (>= 0.3-2)
# SystemRequirements: OpenBugs for functions bugs() and openbugs() or WinBUGS 1.4 for function bugs()
# Maintainer: Uwe Ligges <ligges@statistik.tu-dortmund.de>
# License: GPL-2
# Dialect: R, S-PLUS
# Packaged: 2015-07-29 21:06:15 UTC; ligges
# NeedsCompilation: no
# Repository: CRAN
# Date/Publication: 2015-07-30 00:15:56
