travis:
  secure:
    BINSTAR_TOKEN: MfN3bTmhJkplOvAbQDwPuL2kBnylkHRzJFJyLBRLcCJjN3owQ5OtMzDj5QE5c8zsMtYhxvSavR0FIVztxrZMRUiJ184StJ16jrOE2ql0igkCxorwVlgQUcS4+G6i6Q7CxzzZtIVaiJIe933l1CNE2wp3UccS/AwCOtIrUvI/ffICwPE/RHqzVRkl9qBxaT7xLWMSJDBELspl6wG6lH6bpnIUxtWzCvyz+Sb3CxAyTl3cpjjOK/UwO/917NFEnQ4RpBs3n2PJwB+Rk0g5wSVfRjZJhoB2s0LxpF43RM+5nBLSgWkHr6y9Rq0T/oC4fIvadxDyEVF6n4kTw4q7e1zt1uo3etVAp3ivG2Ib/M8MuDAYN5MYLDgLEAJWffYaAikoUNJmUmRIyoZ4DJa/HZt2Pg6tVW5k9EE4KfbH4rrrev4GVBWGmKr4LnpmVLS8bC5UnM5llJssIBrB2VmzE3jUW7+DEi9kRO1t+cpH2UCAsVq6sQYuYPpDhXzKfN3niTJBR4wUznir/ZI9xlK92H7KQbeDHR/kmzQYRCQh4MLtFccsqznLeM6q0LVDJGCTgJIuiGA4sU3Rm5zRQsW5vbs8tHVT9F07WCh+DdUKKmFTL7RuqVK87fF1I143ynvIvFyhqw6ChKdL3o5tLo7E/f5eqUlCmOtDBLCBhbv77usC9bQ=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
